//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eshop1Entities : DbContext
    {
        public eshop1Entities()
            : base("name=eshop1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tb_Category> Tb_Category { get; set; }
        public virtual DbSet<Tb_OderDetail> Tb_OderDetail { get; set; }
        public virtual DbSet<Tb_Product> Tb_Product { get; set; }
        public virtual DbSet<Tb_User> Tb_User { get; set; }
        public virtual DbSet<Tb_Order> Tb_Order { get; set; }
    }
}
