//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Order()
        {
            this.Tb_OderDetail = new HashSet<Tb_OderDetail>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> OderDate { get; set; }
        public string Address { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_OderDetail> Tb_OderDetail { get; set; }
        public virtual Tb_User Tb_User { get; set; }
    }
}
